### ISSUE TITLE
Adding a new Signal does result in a wrong model

### ISSUE THREAD

**Issue by rsoika** [imixs/open-bpmn#218]
Adding a new signal causes exceptions.
Also the signal default name is not set

```
2023-03-20 20:17:32,321644000 [DefaultActionDispatcher 12] ERROR DefaultGLSPServer - [ERROR] Could not process message:ActionMessage [action=computedBounds, clientId=bpmn-diagram:file:///home/rsoika/git/open-bpmn/open-bpmn.glsp-client/workspace/imixs-test.bpmn]
org.eclipse.glsp.server.types.GLSPServerException: Model element not found! ID: ce8150be-d47c-4419-9ea9-8405283cdcac
	at org.eclipse.glsp.server.types.GLSPServerException.getOrThrow(GLSPServerException.java:58) ~[org.eclipse.glsp.server-1.1.0.RC03.jar:?]
GLSPServerException.java:58
	at org.eclipse.glsp.server.utils.LayoutUtil.applyBounds(LayoutUtil.java:73) ~[org.eclipse.glsp.server-1.1.0.RC03.jar:?]
LayoutUtil.java:73
	at org.eclipse.glsp.server.utils.LayoutUtil.lambda$applyBounds$0(LayoutUtil.java:60) ~[org.eclipse.glsp.server-1.1.0.RC03.jar:?]
LayoutUtil.java:60
	at java.util.ArrayList.forEach(ArrayList.java:1541) ~[?:?]
ArrayList.java:1541
	at org.eclipse.glsp.server.utils.LayoutUtil.applyBounds(LayoutUtil.java:60) ~[org.eclipse.glsp.server-1.1.0.RC03.jar:?]
LayoutUtil.java:60
	at org.eclipse.glsp.server.features.core.model.ComputedBoundsActionHandler.executeAction(ComputedBoundsActionHandler.java:42) ~[org.eclipse.glsp.server-1.1.0.RC03.jar:?]
ComputedBoundsActionHandler.java:42
	at org.eclipse.glsp.server.features.core.model.ComputedBoundsActionHandler.executeAction(ComputedBoundsActionHandler.java:28) ~[org.eclipse.glsp.server-1.1.0.RC03.jar:?]
ComputedBoundsActionHandler.java:28
```

**Comment by rsoika** [comment]
solved with #222
